### ISSUE TITLE
[Bug] Close wikipedia dialog

### ISSUE THREAD

**Issue by matke-84** [jurialmunkey/script.wikipedia#1]
I found a small bug. When I start wikipedia by pressing the button I created, a window opens with a selection of content that I want to select. 
![fffff](https://github.com/jurialmunkey/script.wikipedia/assets/74268331/b089a11d-309b-4aa7-963f-544126d646a7)
When I select content a wikipedia dialog opens. 
![ggffg](https://github.com/jurialmunkey/script.wikipedia/assets/74268331/05a288d5-73bf-428f-a699-87517593f61f)
However, if I don't select anything but turn off the dialog that appears with a selection of content, the wikipedia window appears for a moment. It's actually like closing a wikipedia window that wasn't even open.
![qqq](https://github.com/jurialmunkey/script.wikipedia/assets/74268331/d0faf08e-9454-42da-959b-73d752cdc34d)

**Comment by jurialmunkey** [comment]
I haven't had a chance to look at this yet.

**Comment by jurialmunkey** [comment]
I don't think much can be done from the script side of things. The GUI modal dialog needs to open to perform the search. If the search fails for any reason (e.g. you close the select dialog) then the script closes the modal dialog

You likely can deal with this in the skin with visibility conditions checking if there's a label in control 9901
`<visible>!String.IsEmpty(Control.GetLabel(9901))</visible>`
