### ISSUE TITLE
Default language

### ISSUE THREAD

**Issue by malvinas2** [jurialmunkey/script.wikipedia#2]
Hello, 

thank you for this simple, but great addon! 
Would it be possible to add an entry in the add-on settings, which controls the default language? 

Something like: 
Default language 'english': 
`RunScript(script.wikipedia,wikipedia=Alien,tmdb_type=movie)`  --> returns result in english
`RunScript(script.wikipedia,wikipedia=Alien,tmdb_type=movie,language=fr)` --> returns result in french

**Comment by malvinas2** [comment]
As a workaround I use the following lines within the skin: 

```
	<variable name="language_iso639-1">
		<value condition="String.Contains(System.Language,German)">de</value>
		<value condition="String.Contains(System.Language,French)">fr</value>
		<value condition="String.Contains(System.Language,Italian)">it</value>
		<value condition="String.Contains(System.Language,Spanish)">es</value>
		<value>en</value>
	</variable>
```

```<onclick condition="!String.IsEmpty(ListItem.TvShowTitle)">RunScript(script.wikipedia,wikipedia=$VAR[value_header],tmdb_type=tv,language=$VAR[language_iso639-1])</onclick>```

**Comment by jurialmunkey** [comment]
Note that `tmdb_type` does not work with languages other than English. If you attempt to use it with other languages you will get worse results than if you did not use it at all.

This is partially why I haven't yet implemented an internal language setting.
