### ISSUE TITLE
Too much default transparency makes articles unreadable. In Arctic Fuse skin.

### ISSUE THREAD

**Issue by cg00001** [jurialmunkey/script.wikipedia#4]
Hopefully there is a quick fix for this.
![wiki](https://github.com/jurialmunkey/script.wikipedia/assets/38960370/0bd2d6d0-0aaf-4a63-ad89-a1e9b2ea73c7)

**Comment by jurialmunkey** [comment]
This is a skin issue. Please open issue on Arctic Fuse github:
https://github.com/jurialmunkey/skin.arctic.fuse/issues/new?assignees=&labels=bug&projects=&template=bug_report.yml&title=%5BBUG%5D+Short+Description
