### ISSUE TITLE
Pass currently playing artist as search term

### ISSUE THREAD

**Issue by C-O-D** [jurialmunkey/script.wikipedia#5]
I am trying to pass the artist currently playing artist as search term in my keymap using

RunScript(script.wikipedia,wikipedia=$INFO[MusicPlayer.Artist])

which doesn't work, neither when I am in the music OSD nor on the home screen - what am I doing wrong?

**Comment by jurialmunkey** [comment]
$INFO is part of the skin engine. It's not going to be translated in a keymap. That's going to ask the script to search for the actual string `$INFO[MusicPlayer.Artist]` not whatever the artist is.

You can use a simple python script to import the xbmc module and get the infolabel value.

```python
import xbmc
info = xbmc.getInfoLabel('MusicPlayer.Artist')
xbmc.executebuiltin(f'RunScript(script.wikipedia,wikipedia={info})')
```

Then save it as a `.py` file and runscript it instead

`RunScript(/path/to/my/script.py)`

**Comment by C-O-D** [comment]
Thank you very much, it worked great. Thanks again for the great Wikipedia addon, which makes it possible for me to get some background information about the artists while listening to music - absolutely brilliant!
