### ISSUE TITLE
Feature request: Capture displayed album Wikipedia data to the album .nfo

### ISSUE THREAD

**Issue by fcr** [jurialmunkey/script.wikipedia#8]
The Wikipedia integration with Arctic Zephyr Reloaded is one of its major features for me. It gives access to album information that the Kodi scrappers miss and brings Koi closer to the capabilities of Roon. 
However, if I want to add this information to the album metadata, i have to copy and paste by hand.

Adding the capability for the Wikipedia addon to write this information to an album .nfo would definitely streamline the process.

I am aware the the Arctic Zephyr Reloaded skin will later need to be modified to support this feature if it is ever added.

**Comment by jurialmunkey** [comment]
This is a job for a scraper not a script addon. Addons are not permitted to modify the kodi databases or nfo files. 

There could be an option to save out the text to a file but it doesn't really solve what you're suggesting as you'd still need to copy it over manually into the correct file - at which point, it really isn't saving time (you may as well just go to Wikipedia and copy paste).

**Comment by fcr** [comment]
Thanks for the response.
